# Site settings
permalink: /blog/post/:title.html
paginate: 10
paginate_path: "/blog/page/:num"
title: Mary Rose Cook
email: mary@maryrosecook.com
description: > # this means to ignore newlines until "baseurl:"
  Mary Rose Cook's website.  I write code, make music, work at Hacker
  School and live in New York City.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://maryrosecook.com" # the base hostname & protocol for your site
twitter_username: maryrosecook
github_username:  maryrosecook

# Build settings
gems: [jekyll-paginate]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
